### ISSUE TITLE
Get it working without transpiling?

### ISSUE THREAD

**Issue by jmreicha** [airware/webdriver-mocha-async-await-example#2]
Is it possible to get this code to work without using Babel/transpiling?  I read that v7.0.0 of Node has async/await built in now and wanted to try it out.

**Comment by kidmillions** [comment]
Yeah, it should be easy. Support in Node 7.x is behind a flag right now, but you should be able to add `--harmony_async-await` to your mocha.opts and remove the compiler option.

**Comment by kidmillions** [comment]
@jmreicha I've updated the code and removed the transforms for async/await (using `babel-node-env` now - there are still transforms needed for `import`), so give it a try.
